const express = require('express');

const router = express.Router();
const jwtAuth = require('../../../middlewares/jwt-auth');

const AreaController = require('../../../controllers/customer/area');
const ContactController = require('../../../controllers/customer/contact');

router.get('/cities', AreaController.getCitiesList);

/**
 * @api {get} /api/customer/cities Get Cities List
 * @apiName  Cities List
 * @apiGroup Customer-Common
 *
 *
 * @apiSuccessExample Success-Response:
 *     HTTP/1.1 200 OK
 * {
 *     "success": true,
 *     "code": 200,
 *     "data": {
 *         "cities": [
 *             {
 *                 "_id": "5cd01c1839b32d325085052d",
 *                 "name": "Gurgaon",
 *                 "created_at": "2019-05-06T11:35:52.520Z",
 *                 "updated_at": "2019-05-06T11:35:52.520Z",
 *                 "__v": 0
 *             },
 *             {
 *                 "_id": "5cd02537b1ef5e3bfb165f5c",
 *                 "name": "Gurgaon New",
 *                 "created_at": "2019-05-06T12:14:47.699Z",
 *                 "updated_at": "2019-05-06T12:14:47.699Z",
 *                 "__v": 0
 *             }
 *         ]
 *     }
 * }
 */

router.get('/areas', AreaController.getAreasList);

/**
 * @api {get} /api/customer/areas Get Area List
 * @apiName  Get Area List
 * @apiGroup Customer-Area
 *
 * @apiParam (Query String) {String} city_id id of the city to get its areas.
 *
 * @apiSuccessExample Success-Response:
 *     HTTP/1.1 200 OK
 * {
 *     "success": true,
 *     "code": 200,
 *     "data": {
 *         "city": {
 *             "areas": [
 *                 {
 *                     "_id": "5cd01b02c1a6f3317fd9f072",
 *                     "name": "sector-14",
 *                     "created_at": "2019-05-06T11:31:14.865Z",
 *                     "updated_at": "2019-05-06T11:31:14.865Z",
 *                     "__v": 0
 *                 },
 *                 {
 *                     "_id": "5cd01b0cf03a5831a00732d9",
 *                     "name": "sector-12",
 *                     "created_at": "2019-05-06T11:31:24.523Z",
 *                     "updated_at": "2019-05-06T11:31:24.523Z",
 *                     "__v": 0
 *                 }
 *             ],
 *             "_id": "5cd01c1839b32d325085052d",
 *             "name": "Gurgaon",
 *             "created_at": "2019-05-06T11:35:52.520Z",
 *             "updated_at": "2019-05-06T11:35:52.520Z",
 *             "__v": 0
 *         }
 *     }
 * }
 *
 * @apiError ValidationError Facebook Error.
 *
 * @apiErrorExample Facebook error invalid token:
 * {
 *     "success": false,
 *     "singleStringMessage": "400 - {\"error\":{\"message\":\"Error validating access token: Session has expired on Thursday, 02-May-19 09:00:00 PDT. The current time is Thursday, 09-May-19 05:47:57 PDT.\",\"type\":\"OAuthException\",\"code\":190,\"error_subcode\":463,\"fbtrace_id\":\"AYxofrM9uxc\"}}",
 *     "error": {
 *         "error": {
 *             "message": "Error validating access token: Session has expired on Thursday, 02-May-19 09:00:00 PDT. The current time is Thursday, 09-May-19 05:47:57 PDT.",
 *             "type": "OAuthException",
 *             "code": 190,
 *             "error_subcode": 463,
 *             "fbtrace_id": "AYxofrM9uxc"
 *         }
 *     }
 * }
 */

router.post('/contact-us', ContactController.contactRequest);
/**
 * @api {get} /api/customer/contact-us Contact Us
 * @apiName  Contact Us
 * @apiGroup Customer-Common
 *
 * @apiSuccessExample Success-Response
 *  HTTP/1.1 200 OK
 *  {
 *    "success": true,
 *    "code": 200,
 *    "data": {
 *        "contactRequest": {
 *            "_id": "5e787de42daf030e5c836583",
 *            "name": "test",
 *            "message": "12345",
 *            "email": "test@aapkidokan.com",
 *            "created_at": "2020-03-23T09:14:12.057Z",
 *            "updated_at": "2020-03-23T09:14:12.057Z",
 *            "__v": 0
 *        },
 *        "mailData": {
 *            "envelope": {
 *                "from": "aapkidokan@gmail.com",
 *                "to": [
 *                    "test@aapkidokan.com"
 *                ]
 *            },
 *            "messageId": "<0101017106abc18f-290207e7-5aed-431b-ba00-8a276d06fa19-000000@us-west-2.amazonses.com>",
 *            "response": "0101017106abc18f-290207e7-5aed-431b-ba00-8a276d06fa19-000000",
 *            "raw": {
 *                "type": "Buffer",
 *                "data": [
 *                    67,
 *                    111,
 *                    110,
 *                    116,
 *                    101,
 *                    110,
 *                    116,
 *                    45,
 *                    84,
 *                    121,
 *                    112,
 *                    101,
 *                    58,
 *                    32,
 *                    116,
 *                    101,
 *                    120,
 *                    116,
 *                    47,
 *                    104,
 *                    116,
 *                    109,
 *                    108,
 *                    13,
 *                    10,
 *                    70,
 *                    114,
 *                    111,
 *                    109,
 *                    58,
 *                    32,
 *                    97,
 *                    97,
 *                    112,
 *                    107,
 *                    105,
 *                    100,
 *                    111,
 *                    107,
 *                    97,
 *                    110,
 *                    64,
 *                    103,
 *                    109,
 *                    97,
 *                    105,
 *                    108,
 *                    46,
 *                    99,
 *                    111,
 *                    109,
 *                    13,
 *                    10,
 *                    84,
 *                    111,
 *                    58,
 *                    32,
 *                    115,
 *                    105,
 *                    106,
 *                    117,
 *                    46,
 *                    115,
 *                    97,
 *                    109,
 *                    115,
 *                    111,
 *                    110,
 *                    64,
 *                    101,
 *                    110,
 *                    117,
 *                    107,
 *                    101,
 *                    115,
 *                    111,
 *                    102,
 *                    116,
 *                    119,
 *                    97,
 *                    114,
 *                    101,
 *                    46,
 *                    99,
 *                    111,
 *                    109,
 *                    13,
 *                    10,
 *                    83,
 *                    117,
 *                    98,
 *                    106,
 *                    101,
 *                    99,
 *                    116,
 *                    58,
 *                    32,
 *                    79,
 *                    114,
 *                    100,
 *                    101,
 *                    114,
 *                    32,
 *                    66,
 *                    105,
 *                    108,
 *                    108,
 *                    13,
 *                    10,
 *                    77,
 *                    101,
 *                    115,
 *                    115,
 *                    97,
 *                    103,
 *                    101,
 *                    45,
 *                    73,
 *                    68,
 *                    58,
 *                    32,
 *                    60,
 *                    98,
 *                    50,
 *                    51,
 *                    55,
 *                    56,
 *                    51,
 *                    49,
 *                    55,
 *                    45,
 *                    100,
 *                    50,
 *                    98,
 *                    57,
 *                    45,
 *                    55,
 *                    98,
 *                    55,
 *                    100,
 *                    45,
 *                    99,
 *                    99,
 *                    102,
 *                    55,
 *                    45,
 *                    52,
 *                    51,
 *                    52,
 *                    48,
 *                    48,
 *                    102,
 *                    101,
 *                    57,
 *                    52,
 *                    102,
 *                    102,
 *                    52,
 *                    64,
 *                    103,
 *                    109,
 *                    97,
 *                    105,
 *                    108,
 *                    46,
 *                    99,
 *                    111,
 *                    109,
 *                    62,
 *                    13,
 *                    10,
 *                    67,
 *                    111,
 *                    110,
 *                    116,
 *                    101,
 *                    110,
 *                    116,
 *                    45,
 *                    84,
 *                    114,
 *                    97,
 *                    110,
 *                    115,
 *                    102,
 *                    101,
 *                    114,
 *                    45,
 *                    69,
 *                    110,
 *                    99,
 *                    111,
 *                    100,
 *                    105,
 *                    110,
 *                    103,
 *                    58,
 *                    32,
 *                    113,
 *                    117,
 *                    111,
 *                    116,
 *                    101,
 *                    100,
 *                    45,
 *                    112,
 *                    114,
 *                    105,
 *                    110,
 *                    116,
 *                    97,
 *                    98,
 *                    108,
 *                    101,
 *                    13,
 *                    10,
 *                    68,
 *                    97,
 *                    116,
 *                    101,
 *                    58,
 *                    32,
 *                    77,
 *                    111,
 *                    110,
 *                    44,
 *                    32,
 *                    50,
 *                    51,
 *                    32,
 *                    77,
 *                    97,
 *                    114,
 *                    32,
 *                    50,
 *                    48,
 *                    50,
 *                    48,
 *                    32,
 *                    48,
 *                    57,
 *                    58,
 *                    49,
 *                    52,
 *                    58,
 *                    49,
 *                    49,
 *                    32,
 *                    43,
 *                    48,
 *                    48,
 *                    48,
 *                    48,
 *                    13,
 *                    10,
 *                    77,
 *                    73,
 *                    77,
 *                    69,
 *                    45,
 *                    86,
 *                    101,
 *                    114,
 *                    115,
 *                    105,
 *                    111,
 *                    110,
 *                    58,
 *                    32,
 *                    49,
 *                    46,
 *                    48,
 *                    13,
 *                    10,
 *                    13,
 *                    10,
 *                    60,
 *                    104,
 *                    52,
 *                    62,
 *                    68,
 *                    101,
 *                    97,
 *                    114,
 *                    32,
 *                    83,
 *                    105,
 *                    106,
 *                    117,
 *                    32,
 *                    83,
 *                    97,
 *                    109,
 *                    115,
 *                    111,
 *                    110,
 *                    33,
 *                    60,
 *                    47,
 *                    104,
 *                    52,
 *                    62,
 *                    60,
 *                    112,
 *                    62,
 *                    84,
 *                    104,
 *                    97,
 *                    110,
 *                    107,
 *                    32,
 *                    89,
 *                    111,
 *                    117,
 *                    32,
 *                    70,
 *                    111,
 *                    114,
 *                    32,
 *                    67,
 *                    111,
 *                    110,
 *                    116,
 *                    97,
 *                    99,
 *                    116,
 *                    105,
 *                    110,
 *                    103,
 *                    32,
 *                    85,
 *                    115,
 *                    46,
 *                    32,
 *                    87,
 *                    101,
 *                    32,
 *                    119,
 *                    105,
 *                    108,
 *                    108,
 *                    32,
 *                    71,
 *                    101,
 *                    116,
 *                    32,
 *                    98,
 *                    97,
 *                    99,
 *                    107,
 *                    32,
 *                    61,
 *                    13,
 *                    10,
 *                    116,
 *                    111,
 *                    32,
 *                    121,
 *                    111,
 *                    117,
 *                    32,
 *                    115,
 *                    111,
 *                    111,
 *                    110,
 *                    46,
 *                    60,
 *                    47,
 *                    112,
 *                    62,
 *                    60,
 *                    98,
 *                    114,
 *                    62,
 *                    13,
 *                    10
 *                ]
 *            }
 *        },
 *        "message": "Thank you for Contacting Us"
 *    }
 *}
 *
 */


module.exports = router;
